name: nestle_waters_purelife
description: "This application is used order water online and get all available Pure Life products delivered to customer doorstep."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # internationalization and localization facilities
  flutter_localizations:
    sdk: flutter
  # Internationalization
  intl: ^0.19.0
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # GraphQL client
  graphql_flutter: ^5.2.0
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Service locator
  get_it: ^8.0.3
  # Value equality
  equatable: ^2.0.7
  # Remote API
  http: ^1.3.0
  # Retry asynchronous functions
  retry: ^3.1.2
  # Local cache
  hive: ^2.2.3
  # Makes it easier to use Hive
  hive_flutter: ^1.1.0
  # Functional programming
  dartz: ^0.10.1
  # Print logs
  logger: ^2.5.0
  # Launch url
  url_launcher: ^6.3.1
  # Internet connectivity check
  connectivity_plus: ^6.1.4
  # Annotations for the freezed code-generator
  freezed_annotation: ^3.0.0
  # Create code for JSON serialization and deserialization
  json_annotation: ^4.9.0
  # Screens navigation
  go_router: ^15.1.1

dependency_overrides:
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generation and modular compilation
  build_runner: ^2.4.15
  # Generates TypeAdapters to store any class
  hive_generator: ^2.0.1
  # Mocking in unit testing
  mockito: ^5.4.5
  # Good coding practices
  flutter_lints: ^5.0.0
  # Code generator for models classes
  freezed: ^3.0.6
  # Generate to/from JSON code
  json_serializable: ^6.9.5


flutter:
  generate: true
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  #--------------- LOCAL FONTS ------------------#

