name: nestle_waters_purelife
description: "This application is used order water online and get all available Pure Life products delivered to customer doorstep."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # internationalization and localization facilities
  flutter_localizations:
    sdk: flutter
  # Internationalization
  intl: ^0.19.0
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # GraphQL client
  graphql_flutter: ^5.2.0
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Service locator
  get_it: ^7.7.0
  # Value equality
  equatable: ^2.0.7
  # Remote API
  http: ^1.3.0
  # Retry asynchronous functions
  retry: ^3.1.2
  # Local cache
  hive: ^2.2.3
  # Makes it easier to use Hive
  hive_flutter: ^1.1.0
  # Functional programming
  dartz: ^0.10.1
  # Print logs
  logger: ^2.5.0
  # Launch url in web view
  webview_flutter: ^4.11.0
  # Internet connectivity check
  connectivity_plus: ^6.1.4
  # Annotations for the freezed code-generator
  freezed_annotation: ^3.0.0
  # Create code for JSON serialization and deserialization
  json_annotation: ^4.9.0
  # Screens navigation
  go_router: ^15.1.1
  # Keep internet image in the cache
  cached_network_image: ^3.4.1
  # Video player
  video_player: ^2.9.5
  # Cache data locally
  shared_preferences: ^2.5.3
  # Picking images from the image library
  image_picker: ^1.1.2
  # Request permissions and check their status
  permission_handler: ^12.0.0+1
  # Load configuration at runtime from a .env file
  flutter_dotenv: ^5.2.1
  # Encrypt the data of .env
  envied: ^1.1.1
  # On-device authentication
  local_auth: ^2.3.0
  # Automatically generate a shimmer for widget
  redacted: ^1.0.13
  # Connect to multiple Firebase apps
  firebase_core: ^3.13.0
  # Crash reports in Firebase console
  firebase_crashlytics: ^4.3.5
  # Configure flags remotely in firebase
  firebase_remote_config: ^5.4.3
  # Provides a Google Maps widget
  google_maps_flutter: ^2.12.1
  # Provides location services
  geolocator: ^14.0.0
  # Send OTP via SMS and WhatsApp
  twilio_flutter: ^0.9.0
  # Wallet payments (G-Pay and Apple Pay)
  pay: ^3.2.1
  # Consent Management Platform (CMP)
  onetrust_publishers_native_cmp: ^202504.1.0
  # Push notifications
  pushwoosh_flutter: ^2.3.12
  # App analytics
  adjust_sdk: ^5.1.0
  # State management
  provider: ^6.1.5
  # Deep linking
  app_links: ^6.4.0
  # Version Info
  package_info_plus: ^8.3.0
  # Find locations on the filesystem
  path_provider: ^2.1.5
  # Network calls
  dio: ^5.8.0+1

dependency_overrides:
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generation and modular compilation
  build_runner: ^2.4.15
  # Generates TypeAdapters to store any class
  hive_generator: ^2.0.1
  # Mocking in unit testing
  mockito: ^5.4.5
  # Good coding practices
  flutter_lints: ^5.0.0
  # Code generator for models classes
  freezed: ^3.0.6
  # Generate to/from JSON code
  json_serializable: ^6.9.5
  # Generator for the Envied package
  envied_generator: ^1.1.1


flutter:
  generate: true
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
  - assets/images/user.png
  - dev.env
  - stage.env
  - prod.env

  #--------------- LOCAL FONTS ------------------#

